# Generated by Django 6.0.5 on 2026-05-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Casa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Casa de la Playa, Mi Departamento",
                        max_length=100,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Sala Principal, Dormitorio, Cocina",
                        max_length=100,
                    ),
                ),
                (
                    "casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="domotica.casa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Foco Inteligente 1, Smart TV", max_length=100
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LUZ", "Iluminación"),
                            ("TV", "Televisor / Entretenimiento"),
                            ("AC", "Aire Acondicionado"),
                            ("CAM", "Cámara de Seguridad"),
                        ],
                        default="LUZ",
                        max_length=10,
                    ),
                ),
                ("esta_encendido", models.BooleanField(default=False)),
                (
                    "valor_ajuste",
                    models.IntegerField(
                        default=0,
                        help_text="Para la intensidad de la luz (0-100) o temperatura del AC",
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispositivos",
                        to="domotica.habitacion",
                    ),
                ),
            ],
        ),
    ]
